// Mock Data for Development Preview
import { Role, TaskStatus, LeaveStatus, LeaveType, CarStatus, SubUnitType } from './types';

// Mock Departments
export const mockDepartments = [
  { id: 'dept-1', name: 'ฝ่ายขาย', createdAt: new Date(), updatedAt: new Date() },
  { id: 'dept-2', name: 'การเงิน', createdAt: new Date(), updatedAt: new Date() },
  { id: 'dept-3', name: 'แผนกช่าง', createdAt: new Date(), updatedAt: new Date() },
];

// Mock Sub-Units
export const mockSubUnits = [
  { id: 'sub-1', name: 'เครื่องเช่า', type: SubUnitType.RENTAL, departmentId: 'dept-3', department: mockDepartments[2], createdAt: new Date(), updatedAt: new Date(), _count: { users: 3, tasks: 5 } },
  { id: 'sub-2', name: 'ติดตั้ง', type: SubUnitType.INSTALLATION, departmentId: 'dept-3', department: mockDepartments[2], createdAt: new Date(), updatedAt: new Date(), _count: { users: 4, tasks: 8 } },
  { id: 'sub-3', name: 'ปริ้นเตอร์', type: SubUnitType.PRINTER, departmentId: 'dept-3', department: mockDepartments[2], createdAt: new Date(), updatedAt: new Date(), _count: { users: 2, tasks: 3 } },
];

// Mock Users
export const mockUsers = [
  {
    id: 'user-1',
    employeeId: 'EMP001',
    email: 'admin@example.com',
    password: '$2a$10$example', // hashed "password123"
    name: 'ผู้ดูแลระบบ',
    phone: '081-234-5678',
    avatar: undefined,
    role: Role.ADMIN,
    departmentId: 'dept-3',
    department: mockDepartments[2],
    subUnitId: undefined,
    subUnit: undefined,
    leaveQuota: 15,
    leaveUsed: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-2',
    employeeId: 'EMP002',
    email: 'headtech@example.com',
    password: '$2a$10$example',
    name: 'หัวหน้าแผนกช่าง',
    phone: '081-234-5679',
    avatar: undefined,
    role: Role.HEAD_TECH,
    departmentId: 'dept-3',
    department: mockDepartments[2],
    subUnitId: undefined,
    subUnit: undefined,
    leaveQuota: 15,
    leaveUsed: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-3',
    employeeId: 'EMP003',
    email: 'leader@example.com',
    password: '$2a$10$example',
    name: 'หัวหน้าทีมเครื่องเช่า',
    phone: '081-234-5680',
    avatar: undefined,
    role: Role.LEADER,
    departmentId: 'dept-3',
    department: mockDepartments[2],
    subUnitId: 'sub-1',
    subUnit: mockSubUnits[0],
    leaveQuota: 15,
    leaveUsed: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-4',
    employeeId: 'EMP004',
    email: 'tech1@example.com',
    password: '$2a$10$example',
    name: 'ช่างเทคนิค 1',
    phone: '081-234-5681',
    avatar: undefined,
    role: Role.TECH,
    departmentId: 'dept-3',
    department: mockDepartments[2],
    subUnitId: 'sub-1',
    subUnit: mockSubUnits[0],
    leaveQuota: 15,
    leaveUsed: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-5',
    employeeId: 'EMP005',
    email: 'tech2@example.com',
    password: '$2a$10$example',
    name: 'ช่างเทคนิค 2',
    phone: '081-234-5682',
    avatar: undefined,
    role: Role.TECH,
    departmentId: 'dept-3',
    department: mockDepartments[2],
    subUnitId: 'sub-2',
    subUnit: mockSubUnits[1],
    leaveQuota: 15,
    leaveUsed: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'user-6',
    employeeId: 'EMP006',
    email: 'sales@example.com',
    password: '$2a$10$example',
    name: 'พนักงานขาย',
    phone: '081-234-5683',
    avatar: undefined,
    role: Role.SALES,
    departmentId: 'dept-1',
    department: mockDepartments[0],
    subUnitId: undefined,
    subUnit: undefined,
    leaveQuota: 15,
    leaveUsed: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Cars
export const mockCars = [
  {
    id: 'car-1',
    plateNumber: 'กข-1234',
    licensePlate: 'กข-1234',
    name: 'รถกระบะ Toyota',
    brand: 'Toyota',
    model: 'Hilux Revo',
    year: 2022,
    type: 'กระบะ',
    status: CarStatus.AVAILABLE,
    mileage: 45000,
    description: 'รถกระบะสำหรับงานติดตั้ง',
    lastMaintenance: new Date('2024-11-15'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'car-2',
    plateNumber: 'กค-5678',
    licensePlate: 'กค-5678',
    name: 'รถตู้ Toyota',
    brand: 'Toyota',
    model: 'Commuter',
    year: 2021,
    type: 'รถตู้',
    status: CarStatus.IN_USE,
    mileage: 78000,
    description: 'รถตู้สำหรับขนอุปกรณ์',
    lastMaintenance: new Date('2024-10-20'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'car-3',
    plateNumber: 'กง-9012',
    licensePlate: 'กง-9012',
    name: 'รถเก๋ง Honda',
    brand: 'Honda',
    model: 'City',
    year: 2023,
    type: 'เก๋ง',
    status: CarStatus.AVAILABLE,
    mileage: 15000,
    description: 'รถเก๋งสำหรับงานประสานงาน',
    lastMaintenance: new Date('2024-12-01'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'car-4',
    plateNumber: 'กจ-3456',
    licensePlate: 'กจ-3456',
    name: 'รถกระบะ Isuzu',
    brand: 'Isuzu',
    model: 'D-Max',
    year: 2020,
    type: 'กระบะ',
    status: CarStatus.MAINTENANCE,
    mileage: 120000,
    description: 'รถกระบะอยู่ระหว่างซ่อมบำรุง',
    lastMaintenance: new Date('2024-12-20'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Helper to generate dates
const today = new Date();
const getDate = (daysOffset: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  return d;
};

// Mock Tasks
export const mockTasks = [
  {
    id: 'task-1',
    jobNumber: 'JOB-2024-001',
    title: 'ติดตั้งเครื่องถ่ายเอกสาร Canon',
    description: 'ติดตั้งเครื่องถ่ายเอกสาร Canon iR-ADV C5535 พร้อมตั้งค่าเครือข่าย',
    location: 'บริษัท ABC จำกัด ชั้น 5',
    customerName: 'บริษัท ABC จำกัด',
    customerPhone: '02-123-4567',
    startDate: getDate(0),
    endDate: getDate(0),
    scheduledDate: getDate(0),
    startTime: '09:00',
    endTime: '12:00',
    status: TaskStatus.IN_PROGRESS,
    isLoop: false,
    priority: 2,
    subUnitId: 'sub-2',
    subUnit: mockSubUnits[1],
    carId: 'car-2',
    car: mockCars[1],
    createdById: 'user-6',
    createdBy: mockUsers[5],
    assignments: [
      { id: 'assign-1', taskId: 'task-1', userId: 'user-5', user: mockUsers[4], isPrimary: true, isLead: true },
    ],
    images: [],
    printerLogs: [],
    createdAt: getDate(-2),
    updatedAt: new Date(),
  },
  {
    id: 'task-2',
    jobNumber: 'JOB-2024-002',
    title: 'ซ่อมปริ้นเตอร์ HP LaserJet',
    description: 'ปริ้นเตอร์ไม่ดึงกระดาษ ต้องตรวจสอบลูกยาง',
    location: 'บริษัท XYZ ชั้น 3',
    customerName: 'บริษัท XYZ จำกัด',
    customerPhone: '02-987-6543',
    startDate: getDate(1),
    endDate: getDate(1),
    scheduledDate: getDate(1),
    startTime: '13:00',
    endTime: '16:00',
    status: TaskStatus.WAITING,
    isLoop: false,
    priority: 3,
    subUnitId: 'sub-3',
    subUnit: mockSubUnits[2],
    carId: undefined,
    car: undefined,
    createdById: 'user-6',
    createdBy: mockUsers[5],
    assignments: [],
    images: [],
    printerLogs: [],
    createdAt: getDate(-1),
    updatedAt: new Date(),
  },
  {
    id: 'task-3',
    jobNumber: 'JOB-2024-003',
    title: 'บำรุงรักษาเครื่องเช่าประจำเดือน',
    description: 'ตรวจสอบและบำรุงรักษาเครื่องถ่ายเอกสารเช่า 5 เครื่อง',
    location: 'บริษัท DEF ชั้น 10',
    customerName: 'บริษัท DEF จำกัด (มหาชน)',
    customerPhone: '02-555-1234',
    startDate: getDate(-1),
    endDate: getDate(-1),
    scheduledDate: getDate(-1),
    startTime: '09:00',
    endTime: '17:00',
    status: TaskStatus.DONE,
    isLoop: false,
    priority: 1,
    subUnitId: 'sub-1',
    subUnit: mockSubUnits[0],
    carId: 'car-1',
    car: mockCars[0],
    createdById: 'user-3',
    createdBy: mockUsers[2],
    assignments: [
      { id: 'assign-2', taskId: 'task-3', userId: 'user-4', user: mockUsers[3], isPrimary: true, isLead: true },
    ],
    images: [
      { id: 'img-1', taskId: 'task-3', url: '/placeholder-image.jpg', imageType: 'AFTER', uploadedBy: 'user-4' },
    ],
    printerLogs: [],
    completedAt: getDate(-1),
    createdAt: getDate(-3),
    updatedAt: getDate(-1),
  },
  {
    id: 'task-4',
    jobNumber: 'JOB-2024-004',
    title: 'ติดตั้งระบบพิมพ์ใหม่',
    description: 'ติดตั้งเครื่องพิมพ์ใหม่ 3 เครื่องพร้อม Network Setup',
    location: 'โรงแรม Grand Palace',
    customerName: 'โรงแรม Grand Palace',
    customerPhone: '02-888-9999',
    startDate: getDate(2),
    endDate: getDate(2),
    scheduledDate: getDate(2),
    startTime: '10:00',
    endTime: '15:00',
    status: TaskStatus.WAITING,
    isLoop: false,
    priority: 2,
    subUnitId: 'sub-2',
    subUnit: mockSubUnits[1],
    carId: undefined,
    car: undefined,
    createdById: 'user-6',
    createdBy: mockUsers[5],
    assignments: [],
    images: [],
    printerLogs: [],
    createdAt: getDate(0),
    updatedAt: new Date(),
  },
  {
    id: 'task-5',
    jobNumber: 'JOB-2024-005',
    title: 'เปลี่ยนหมึกและตรวจสอบเครื่อง',
    description: 'เปลี่ยนหมึก Toner และตรวจสอบคุณภาพการพิมพ์',
    location: 'ธนาคาร ABC สาขาสีลม',
    customerName: 'ธนาคาร ABC',
    customerPhone: '02-111-2222',
    startDate: getDate(3),
    endDate: getDate(3),
    scheduledDate: getDate(3),
    startTime: '14:00',
    endTime: '16:00',
    status: TaskStatus.WAITING,
    isLoop: false,
    priority: 1,
    subUnitId: 'sub-1',
    subUnit: mockSubUnits[0],
    carId: undefined,
    car: undefined,
    createdById: 'user-3',
    createdBy: mockUsers[2],
    assignments: [],
    images: [],
    printerLogs: [],
    createdAt: getDate(0),
    updatedAt: new Date(),
  },
  {
    id: 'task-6',
    jobNumber: 'JOB-2024-006',
    title: 'ซ่อมเครื่องถ่ายเอกสาร (งานยกเลิก)',
    description: 'ลูกค้ายกเลิกงานเนื่องจากซื้อเครื่องใหม่',
    location: 'บริษัท Test',
    customerName: 'บริษัท Test จำกัด',
    customerPhone: '02-000-0000',
    startDate: getDate(-5),
    endDate: getDate(-5),
    scheduledDate: getDate(-5),
    startTime: '09:00',
    endTime: '12:00',
    status: TaskStatus.CANCELLED,
    isLoop: false,
    priority: 1,
    subUnitId: 'sub-1',
    subUnit: mockSubUnits[0],
    carId: undefined,
    car: undefined,
    createdById: 'user-6',
    createdBy: mockUsers[5],
    assignments: [],
    images: [],
    printerLogs: [],
    createdAt: getDate(-7),
    updatedAt: getDate(-5),
  },
];

// Mock Leaves
export const mockLeaves = [
  {
    id: 'leave-1',
    userId: 'user-4',
    user: mockUsers[3],
    type: LeaveType.SICK,
    status: LeaveStatus.APPROVED,
    startDate: getDate(-10),
    endDate: getDate(-9),
    totalDays: 2,
    reason: 'ไม่สบาย เป็นไข้',
    approvedById: 'user-3',
    approver: mockUsers[2],
    approverNote: 'อนุมัติ',
    approvedAt: getDate(-10),
    createdAt: getDate(-11),
    updatedAt: getDate(-10),
  },
  {
    id: 'leave-2',
    userId: 'user-5',
    user: mockUsers[4],
    type: LeaveType.PERSONAL,
    status: LeaveStatus.PENDING,
    startDate: getDate(5),
    endDate: getDate(5),
    totalDays: 1,
    reason: 'ธุระส่วนตัว',
    approvedById: null,
    approver: null,
    approverNote: null,
    approvedAt: null,
    createdAt: getDate(-1),
    updatedAt: getDate(-1),
  },
  {
    id: 'leave-3',
    userId: 'user-4',
    user: mockUsers[3],
    type: LeaveType.VACATION,
    status: LeaveStatus.PENDING,
    startDate: getDate(10),
    endDate: getDate(12),
    totalDays: 3,
    reason: 'ลาพักผ่อนประจำปี',
    approvedById: null,
    approver: null,
    approverNote: null,
    approvedAt: null,
    createdAt: getDate(0),
    updatedAt: getDate(0),
  },
];

// Mock Notifications
export const mockNotifications = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: 'งานใหม่รอมอบหมาย',
    message: 'มีงาน JOB-2024-002 รอมอบหมายช่าง',
    type: 'TASK',
    isRead: false,
    createdAt: getDate(-1),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: 'คำขอลารออนุมัติ',
    message: 'ช่างเทคนิค 2 ขอลา 1 วัน รอการอนุมัติ',
    type: 'LEAVE',
    isRead: false,
    createdAt: getDate(-1),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    title: 'งานเสร็จสิ้น',
    message: 'งาน JOB-2024-003 เสร็จสิ้นเรียบร้อย',
    type: 'TASK',
    isRead: true,
    createdAt: getDate(-1),
  },
];

// Mock Dashboard Stats
export const mockDashboardStats = {
  totalTasks: 6,
  waitingTasks: 3,
  inProgressTasks: 1,
  completedTasks: 1,
  cancelledTasks: 1,
  todayTasks: 1,
  pendingLeaves: 2,
  availableCars: 2,
};

export const mockLeaderDashboardStats = {
  ...mockDashboardStats,
  teamMembersCount: 4,
  teamOnLeaveToday: 0,
  pendingLeaveRequests: 2,
};

// Auth helper
export function findUserByEmail(email: string) {
  return mockUsers.find(u => u.email === email);
}

export function findUserById(id: string) {
  return mockUsers.find(u => u.id === id);
}
